### ISSUE TITLE
Cannot run gem command

### ISSUE THREAD

**Issue by JunichiIto** [arton/RScript22#8] opened 2017-03-10 22:53 UTC
I installed Ruby 2.4 with "Ruby-2.4.0 (x64-mswin64_100) Microsoft Installer Package (2016-12-24 revision 57164)" and add `C:\Program Files\Ruby-2.4-x64\bin` to PATH. But I cannot run gem command:

```
>gem -v
C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': 126: 指定されたモジュ ールが見つかりません。   - C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/x64-mswin64_100/psych.so (LoadError)
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/psych.rb:8:in `<top (required)>'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/yaml.rb:6:in `<top (required)>'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems.rb:700:in `load_yaml'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/config_file.rb:340:in `load_file'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/config_file.rb:202:in `initialize'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `new'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `do_configuration'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/gem_runner.rb:40:in `run'
        from C:/Program Files/Ruby-2.4-x64/bin/gem.cmd:29:in `<main>'
```

The file `C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/x64-mswin64_100/psych.so` exists. 

<img width="842" alt="screen shot 2017-03-11 at 7 51 47" src="https://cloud.githubusercontent.com/assets/1148320/23816347/abfb1d54-062f-11e7-91e8-329bf83fb3e7.png">

How can I run gem command?

**Comment by arton** [comment] 2017-03-10 23:58
Hi, thanks for your report.
However, it's curious because I can't reproduce it.
I wonder if you could run gem from "Ruby-2.4 console" in 'Ruby-2.4-x64' on start menu, and tell me the result.
Regards

**Comment by JunichiIto** [comment] 2017-03-11 02:27
> I wonder if you could run gem from "Ruby-2.4 console" in 'Ruby-2.4-x64' on start menu, and tell me the result.

I got the same result:

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Program Files\Ruby-2.4-x64\bin>gem -v
C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': 126: 指定されたモジュ ールが見つかりません。   - C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/x64-mswin64_100/psych.so (LoadError)
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/psych.rb:8:in `<top (required)>'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/yaml.rb:6:in `<top (required)>'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems.rb:700:in `load_yaml'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/config_file.rb:340:in `load_file'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/config_file.rb:202:in `initialize'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `new'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `do_configuration'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/gem_runner.rb:40:in `run'
        from C:/Program Files/Ruby-2.4-x64/bin/gem.cmd:29:in `<main>'

C:\Program Files\Ruby-2.4-x64\bin>
```

FYI, Running `require 'yaml'` and `require 'psych'` in irb fails too:

```
C:\Program Files\Ruby-2.4-x64\bin>irb
irb(main):001:0> require 'yaml'
C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
LoadError: 126: 指定されたモジュールが見つかりません。   - C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/x64-mswin64_100/psych.so
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/psych.rb:8:in `<top (required)>'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/yaml.rb:6:in `<top (required)>'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from (irb):1
        from C:/Program Files/Ruby-2.4-x64/bin/irb.cmd:19:in `<main>'
irb(main):002:0> require 'psych'
LoadError: 126: 指定されたモジュールが見つかりません。   - C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/x64-mswin64_100/psych.so
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/psych.rb:8:in `<top (required)>'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby-2.4-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from (irb):2
        from C:/Program Files/Ruby-2.4-x64/bin/irb.cmd:19:in `<main>'
irb(main):003:0>
```

**Comment by arton** [comment] 2017-03-11 11:17
It's curious, because if you ran ruby related command such as irb from 'ruby console', the stack trace should be like this:

```
 LoadError: cannot load such file -- abc
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from (irb):1
        from C:/PROGRA~1/RUBY-2~1.4-X/bin/irb.cmd:19:in `<main>'

```
Because 'ruby console' changes the path name of 'program files'  to its NTFS short name.
I believe rubygems is not WIndows friendly by careless of  directory name with spaces.

What is your filesystem ?

Regards
arton

**Comment by JunichiIto** [comment] 2017-03-11 20:34
My file system is NTFS.

<img width="417" alt="screen shot 2017-03-12 at 5 28 36" src="https://cloud.githubusercontent.com/assets/1148320/23826689/1f75bb9e-06e5-11e7-898b-4ae36ac2ab9f.png">

And when I run `gem -v` from Ruby-2.4 (Administrator) console, I got the stack trace below:

```
C:\Users\JunichiIto>gem -v
C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': 126: 指定されたモジュールが見つかりません。   - C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/x64-mswin64_100/psych.so (LoadError)
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/psych.rb:8:in `<top (required)>'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/yaml.rb:6:in `<top (required)>'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems.rb:700:in `load_yaml'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/config_file.rb:340:in `load_file'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/config_file.rb:202:in `initialize'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `new'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `do_configuration'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/gem_runner.rb:40:in `run'
        from C:/PROGRA~1/RUBY-2~1.4-X/bin/gem.cmd:29:in `<main>'

C:\Users\JunichiIto>
```

It is different from "Ruby-2.4 console", but I still got error.

**Comment by arton** [comment] 2017-03-12 02:35
I don't understand why your Ruby console (administsrator) can run as I expected for short name, but Ruby console can't.
I think your PATH or other related environmetal variable such as RUBYLIB was mal constructed. Therefore ruby loads with wrong version of required DLL for loading Psych.so or yaml.so.

Please run step by step as below.

1. open command prompt
2. set PATH=C:/PROGRA~1/RUBY-2~1.4-X/bin;C:\Windows;C:\Windows\System32
3. gem -v

Regards

**Comment by JunichiIto** [comment] 2017-03-15 04:25
I tried it, but it did not work:

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\JunichiIto>echo "%PATH%"
"C:\oracle\ora81\bin;C:\Program Files (x86)\Oracle\jre\1.1.7\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\JunichiIto\AppData\Local\atom\bin;C:\Users\JunichiIto\AppData\Local\Microsoft\WindowsApps"

C:\Users\JunichiIto>set PATH=C:\PROGRA~1\RUBY-2~1.4-X\bin;%PATH%

C:\Users\JunichiIto>echo "%PATH%"
"C:\PROGRA~1\RUBY-2~1.4-X\bin;C:\oracle\ora81\bin;C:\Program Files (x86)\Oracle\jre\1.1.7\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\JunichiIto\AppData\Local\atom\bin;C:\Users\JunichiIto\AppData\Local\Microsoft\WindowsApps"

C:\Users\JunichiIto>gem -v
C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': 126: 指定されたモジュールが見つ かりません。   - C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/x64-mswin64_100/psych.so (LoadError)
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/psych.rb:8:in `<top (required)>'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/yaml.rb:6:in `<top (required)>'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems.rb:700:in `load_yaml'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/config_file.rb:340:in `load_file'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/config_file.rb:202:in `initialize'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `new'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `do_configuration'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/gem_runner.rb:40:in `run'
        from C:/PROGRA~1/RUBY-2~1.4-X/bin/gem.cmd:29:in `<main>'

C:\Users\JunichiIto>
```

**Comment by arton** [comment] 2017-03-15 22:38
Don't you try as I mentioned?
set PATH=C:/PROGRA1/RUBY-21.4-X/bin;C:\Windows;C:\Windows\System32

**Comment by JunichiIto** [comment] 2017-03-16 01:23
Okay, I did so. Please review the results below:

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\JunichiIto>echo "%PATH%"
"C:\oracle\ora81\bin;C:\Program Files (x86)\Oracle\jre\1.1.7\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\JunichiIto\AppData\Local\atom\bin;C:\Users\JunichiIto\AppData\Local\Microsoft\WindowsApps"

C:\Users\JunichiIto>set PATH=C:/PROGRA~1/RUBY-2~1.4-X/bin;C:\Windows;C:\Windows\System32

C:\Users\JunichiIto>echo "%PATH%"
"C:/PROGRA~1/RUBY-2~1.4-X/bin;C:\Windows;C:\Windows\System32"

C:\Users\JunichiIto>gem -v
C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': 126: 指定されたモジュールが見つ かりません。   - C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/x64-mswin64_100/psych.so (LoadError)
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/psych.rb:8:in `<top (required)>'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/yaml.rb:6:in `<top (required)>'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems.rb:700:in `load_yaml'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/config_file.rb:340:in `load_file'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/config_file.rb:202:in `initialize'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `new'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `do_configuration'
        from C:/PROGRA~1/RUBY-2~1.4-X/lib/ruby/2.4.0/rubygems/gem_runner.rb:40:in `run'
        from C:/PROGRA~1/RUBY-2~1.4-X/bin/gem.cmd:29:in `<main>'

C:\Users\JunichiIto>
```

**Comment by arton** [comment] 2017-03-18 19:31
Do you install / use anti-virus software?
It seems that an anti virus software rejects to load the dll with extension '.so'.

**Comment by JunichiIto** [comment] 2017-03-18 21:06
Thank you for your continuous support. I uninstalled McAfee and disabled Windows Defender, but got the same result.

**Comment by arton** [comment] 2017-03-19 01:16
Ummmm, it puzzled.
At this point:
1.you installed 'Ruby-2.4.0 (x64-mswin64_100) Microsoft Installer Package (2016-12-24 revision 57164)' on your Windows10 x64.
2.With installed ruby/bin and system default path, it can't load psych.so (at least ruby itself can run)
3.However, psych.so is correct location and size.
4.Any anti-virus solution is not there.

I can't figure out what is happened.
Can you load other shared object?
For example, in your plain console (with ruby and windows PATH only), what the result of the output of below command.

> ruby -rsocket -w -e 'p Socket'
Socket  <----- expected result

Thank you for your cooperation.

**Comment by arton** [comment] 2017-03-19 01:24
Or what is in your gemrc?

**Comment by arton** [comment] 2017-03-19 01:52
At least Windows Defender is not harmful. Because I tested with it.
I have no idea for McAfee.
Thank you for your cooperation and please restore their activity.

**Comment by JunichiIto** [comment] 2017-03-19 21:06
`ruby -rsocket -w -e 'p Socket'` seems OK:

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\JunichiIto>set PATH=C:/PROGRA~1/RUBY-2~1.4-X/bin;C:\Windows;C:\Windows\System32

C:\Users\JunichiIto>ruby -rsocket -w -e 'p Socket'
Socket

C:\Users\JunichiIto>
```

And I have no .gemrc files:

```
C:\Users\JunichiIto>dir
 ドライブ C のボリューム ラベルがありません。
 ボリューム シリアル番号は DCBD-3B40 です

 C:\Users\JunichiIto のディレクトリ

2017/03/20  05:57    <DIR>          .
2017/03/20  05:57    <DIR>          ..
2017/03/11  07:43    <DIR>          .atom
2015/10/23  11:21    <DIR>          .kindle
2017/03/20  05:57    <DIR>          Contacts
2017/03/20  05:57    <DIR>          Desktop
2017/03/20  05:57    <DIR>          Documents
2017/03/20  05:57    <DIR>          Downloads
2017/03/20  05:57    <DIR>          Favorites
2017/03/20  05:57    <DIR>          Links
2017/03/20  05:57    <DIR>          Music
2017/03/11  08:07    <DIR>          OneDrive
2017/03/20  05:57    <DIR>          Pictures
2017/03/20  05:57    <DIR>          Saved Games
2017/03/20  05:57    <DIR>          Searches
2017/03/20  05:57    <DIR>          Videos
               0 個のファイル                   0 バイト
              16 個のディレクトリ  48,432,062,464 バイトの空き領域

C:\Users\JunichiIto>echo "%HOMEPATH%"
"\Users\JunichiIto"
```

I searched .gemrc through C drive, but nothing was found.

**Comment by arton** [comment] 2017-03-24 23:15
I'm stuck, I can't figure out what was happened.
Thank you for your cooperation to search the cause.
I will make Ruby-3.4.1 soon, I wonder if you could try it.

I close this issue, because it's not an issued of RScript22 but a packaging.

**Closed as completed by arton** 2017-03-24 23:15 UTC

**Comment by JunichiIto** [comment] 2017-03-25 23:29
I understood. I appreciate your support.
